"""empty message

Revision ID: 5be17b32dfdf
Revises: d247fffb1e20
Create Date: 2025-01-17 17:32:28.193448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be17b32dfdf'
down_revision: Union[str, None] = 'd247fffb1e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'books_users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books_users', type_='unique')
    # ### end Alembic commands ###
