"""empty message

Revision ID: a7b174386bb8
Revises: 92b479ede898
Create Date: 2025-01-11 18:07:50.924927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b174386bb8'
down_revision: Union[str, None] = '92b479ede898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['id'])
    op.add_column('books', sa.Column('author_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'books', ['id'])
    op.drop_constraint('books_author_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    op.drop_column('books', 'author')
    op.create_unique_constraint(None, 'books_genres', ['id'])
    op.create_unique_constraint(None, 'genres', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_constraint(None, 'books_genres', type_='unique')
    op.add_column('books', sa.Column('author', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_author_fkey', 'books', 'authors', ['author'], ['id'])
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'author_id')
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
